### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by juriansluiman** [Soflomo/Purifier#7]
As noted in #5 I am not part of Solfomo anymore and have less time to be involved in the maintenance of Soflomo\Purifier. @Saeven suggested he could help in maintenance.

@Seaven what you think of the open PRs #2 #3 and #4? All three look like a great addition but with kind of overlap. Can you manage those to be joint and merged? As said, happy to give you collaborator rights to finish off those contributions.

**Comment by stefanotorresi** [comment]
@juriansluiman I currently use this module regularly and I need this issue to be dealt with.
If Soflomo is not willing to mantain it, I'd explore the possibility to make kind of an official fork and redirect to it to from this repo and in packagist. What do you think?

**Comment by stefanotorresi** [comment]
@jonday-mayden I dont know, I was waiting for response from the soflomo folks

**Comment by jurreantonisse** [comment]
@stefanotorresi Hello I am from Soflomo. I do not have the expertise to maintain this module. @juriansluiman made this. With his permission I am OK if other people like you guys take over maintenance, he has still rights to grant permission or transfer the repo.

**Comment by stefanotorresi** [comment]
@jurreantonisse we can proceed in three different ways:

1. I'm given write access to the repo and I continue maintenance here.
2. The repo is transfered to me and I continue maintenance there. I'm not sure what this would entails on packagist, but we'll find out.
3. I submit a PR where in the readme we state clear in the README that this repo is discontinued and has been replaced by my fork, then @juriansluiman should merge the PR, mark the repo as abandonend on packagist and disable the github issue tracker.

Pick one and let me know.

**Comment by jurreantonisse** [comment]
@stefanotorresi I am sure you and @juriansluiman and you can decide whats best. As stated before I cannot make this decision myself.

**Comment by stefanotorresi** [comment]
ok @jurreantonisse i guess we have to wait for @juriansluiman then ;)

**Comment by juriansluiman** [comment]
Closing as discussed with @stefanotorresi
